global using System.IO.Abstractions.TestingHelpers;
global using System.Security.Cryptography;
global using System.Text;
global using NSubstitute;
global using Serilog.Sinks.File.Encrypt.Cli.Commands;
global using Shouldly;
global using Spectre.Console.Cli;
global using Spectre.Console.Testing;
global using Xunit;
